---
- assert:
    that: >
      item.split(' ')[0] in ['MAINTAINER', 'RUN', 'CMD', 'LABEL', 'EXPOSE',
                             'ENV', 'ADD', 'COPY', 'ENTRYPOINT', 'VOLUME',
                             'USER', 'WORKDIR', 'ARG', 'ONBUILD', 'STOPSIGNAL']
  with_items: "{{ instructions }}"
  tags: ['validate']

- name: make dockerfile
  template: "{{ template_options | combine({ 'src': 'Dockerfile', 'dest': dest }) }}"
  tags: ['render']
