---
- assert:
    that: >
      item.split(' ')[0] in
      ['MAINTAINER', 'RUN', 'CMD', 'LABEL', 'EXPOSE', 'ENV', 'ADD', 'COPY',
      'ENTRYPOINT', 'VOLUME', 'USER', 'WORKDIR', 'ARG', 'ONBUILD', 'STOPSIGNAL']
  with_items: "{{ instructions }}"
  tags: ['validate']

- name: make dockerfile
  template:
    src: Dockerfile
    dest: "{{ dest }}"
    owner: "{{ owner | default(omit) }}"
    group: "{{ group | default(omit) }}"
    mode: "{{ mode | default(omit) }}"
    backup: "{{ backup | default(omit) }}"
    force: "{{ force | default(omit) }}"
    validate: "{{ validate | default(omit) }}"
    selevel: "{{ selevel | default(omit) }}"
    serole: "{{ serole | default(omit) }}"
    setype: "{{ setype | default(omit) }}"
    seuser: "{{ seuser | default(omit) }}"
  tags: ['render']
